name: test_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.0.11
  file_picker: ^5.1.0
  uuid: ^3.0.5
  reorderable_grid: ^1.0.10
  settings_ui: ^2.0.2
  table_calendar: ^3.1.2
  flutter_speed_dial: ^6.0.0
  json_annotation: ^4.5.0
  english_words: ^4.0.0
  provider: ^6.1.2
  flutter_tts: ^3.3.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  flutter_login: ^5.0.0
  firebase_storage: ^11.6.0
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  fluttertoast: ^8.2.8
  top_snackbar_flutter: ^3.1.0
  audioplayers: ^6.1.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  scribble: ^0.10.0+1
  flutter_libphonenumber: ^2.3.3
  animate_gradient: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/Screenshot 2024-07-29 at 4.31.43 PM.png
    - assets/board_info/board.json
    - assets/imgs/OneDrive_Folder_Icon.png
    - assets/imgs/sun.png
    - assets/board_info/pictograms.json
    - assets/imgs/temp_logo.jpg
    - assets/imgs/sad.png
    - assets/imgs/happy.png
    - assets/imgs/bored.png
    - assets/imgs/angry.png
    - assets/imgs/tired.png
    - assets/imgs/nervous.png
    - assets/imgs/final_spinner.png
    - assets/sound_effects/spinning-fidget-spinner-23292.mp3
    - assets/songs/Twinnkle, Twinkle, Little Star.mp3
    - assets/songs/HumptyDumpty.mp3
    - assets/songs/alphabet song.mp3
    - assets/songs/music.json
    - assets/songs/Screenshot 2024-09-09 at 7.49.23 PM.png
    - assets/songs/Screenshot 2024-09-09 at 7.49.55 PM.png
    - assets/songs/Screenshot 2024-09-09 at 7.50.11 PM.png
    - assets/songs/dreamstime_xs_24653504.jpg
    - assets/songs/im-a-little-teapot.jpg
    - assets/songs/im-a-little-teapot.mp3
    - assets/songs/images.jpeg
    - assets/songs/png-clipart-three-child-plays-baseball-baseball-field-cartoon-child-baseball-kids-sport-photography.png
    - assets/songs/pop-goes-the-weasel.mp3
    - assets/songs/Pop-Goes-the-Weasel-Nursery-Rhyme-for-Kids.jpg
    - assets/songs/rain-rain.mp3
    - assets/songs/Rowgo.mp3
    - assets/songs/take-me-out-to-the-ballgame.mp3


